import streamlit as st  
from functions import *
import base64
import random


def display_pdf(uploaded_file):

    """
    Display a PDF file that has been uploaded to Streamlit.

    The PDF will be displayed in an iframe, with the width and height set to 700x1000 pixels.

    Parameters
    ----------
    uploaded_file : UploadedFile
        The uploaded PDF file to display.

    Returns
    -------
    None
    """
    # Read file as bytes:
    bytes_data = uploaded_file.getvalue()
    
    # Convert to Base64
    base64_pdf = base64.b64encode(bytes_data).decode('utf-8')
    
    # Embed PDF in HTML
    pdf_display = f'<iframe src="data:application/pdf;base64,{base64_pdf}" width="700" height="900" type="application/pdf"></iframe>'
    
    # Display file
    st.markdown(pdf_display, unsafe_allow_html=True)


    """
    Load the streamlit page with two columns. The left column contains frequently asked questions and answers generated by the RAG from the artiles in the pdf urls provided. The right column contains a chatbot that lets the user interact with a chatbot.

    Returns:
        col1: The left column Streamlit object of frequently asked questions with answers.
        col2: The right column Streamlit object of a chatbot the user can interact with.
    """

def load_streamlit_page():

    st.set_page_config(layout="wide", page_title="MotorFanz FAQ")
    st.markdown("<h1 style='text-align: center;'>MotorFanz FAQ</h1>", unsafe_allow_html=True)
    # Design page layout with 2 columns: File uploader on the left, and other interactions on the right.
    col1, col2 = st.columns([0.7, 0.3], gap="small")#,border=True

    return col1, col2

# Make a streamlit page
col1, col2= load_streamlit_page()

# Ppopulate the left column with questions from the questions.txt file and answer them with the RAG
    # Using the 
with col1:
    st.markdown("<h2 style='text-align: center; text-decoration:underline;'>Frequently Asked Questions</h2>", unsafe_allow_html=True)
    
    # fileLoc="pdfData\questions.txt"
    with open("pdfData\questions.txt") as questionFile:
        questions = questionFile.readlines()
    
    answer=[]
    for question in random.choices(questions, k=5): 
        answer.append(query_document(vectorstore = st.session_state.vector_store, 
                                    query = question,
                                    # api_key = st.session_state.api_key
                                    ))
    placeholder = st.empty()
    placeholder = st.write(answer)                
    st.write("Trying somethingTrying somethingTrying somethingTrying somethingTrying somethingTrying something")
    st.write("* Trying somethingTrying somethingTrying somethingTrying somethingTrying somethingTrying something")



# Process the input
# if uploaded_file is not None:
with col2:
    st.markdown("<h2 style='text-align: center; text-decoration:underline;'>Chat with Motory</h2>", unsafe_allow_html=True)


# Generate answer
# with col1:
    
    
#     if st.button("Generate table"):
#         with st.spinner("Generating answer"):
#             # Load vectorstore:
#             for i in range(5):

#                 answer = query_document(vectorstore = st.session_state.vector_store, 
#                                         query = "Give me the title, summary, publication date, and authors of the research paper.",
#                                         api_key = st.session_state.api_key)
                                
#                 placeholder = st.empty()
#                 placeholder = st.write(answer)